//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCAROS7.DoItSearch.Decktop.CSharp {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strLang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCAROS7.DoItSearch.Decktop.CSharp.strLang", typeof(strLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel (&amp;C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please type searching keyword과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Type_Keyword {
            get {
                return ResourceManager.GetString("Error_Type_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string exitToolStripMenuItem {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup searching keyword. You can split by &apos;,&apos; symbol (comma).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_1 {
            get {
                return ResourceManager.GetString("Help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Example : Twitter,TwTwitter,#Twiter (Support # Searching)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_2 {
            get {
                return ResourceManager.GetString("Help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup searching waiting interval due next searching.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_3 {
            get {
                return ResourceManager.GetString("Help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed option will be waiting fixed time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_4 {
            get {
                return ResourceManager.GetString("Help_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random option will be waiting random time until setup time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_5 {
            get {
                return ResourceManager.GetString("Help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can edit setup time, click &apos;Searching Interval&apos; at top.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_6 {
            get {
                return ResourceManager.GetString("Help_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you want to load saved settings (Include Language),과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_7 {
            get {
                return ResourceManager.GetString("Help_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just checking &apos;Settings&apos; -&gt; &apos;Load at Startup&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_8 {
            get {
                return ResourceManager.GetString("Help_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Powered by hominlab@minnote.net과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_9 {
            get {
                return ResourceManager.GetString("Help_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help (&amp;H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_Label {
            get {
                return ResourceManager.GetString("Help_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Interval_Type {
            get {
                return ResourceManager.GetString("Interval_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success to Load!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Load_Loaded {
            get {
                return ResourceManager.GetString("Load_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load. Please check log.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Load_Loaded_Error {
            get {
                return ResourceManager.GetString("Load_Loaded_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load at Startup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loadAtStartToolStripMenuItem {
            get {
                return ResourceManager.GetString("loadAtStartToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loadToolStripMenuItem {
            get {
                return ResourceManager.GetString("loadToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Form Initialize or Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_abnormal {
            get {
                return ResourceManager.GetString("Log_abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Load at Startup Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Changed_LoadAtStart {
            get {
                return ResourceManager.GetString("Log_Changed_LoadAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank Keyword과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Error_Blank_Keyword {
            get {
                return ResourceManager.GetString("Log_Error_Blank_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Settings Error :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Error_Load {
            get {
                return ResourceManager.GetString("Log_Error_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Error :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Error_Process {
            get {
                return ResourceManager.GetString("Log_Error_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings Error :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Error_Save {
            get {
                return ResourceManager.GetString("Log_Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application launched과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Form_Load {
            get {
                return ResourceManager.GetString("Log_Form_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Lang_Change {
            get {
                return ResourceManager.GetString("Log_Lang_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Load {
            get {
                return ResourceManager.GetString("Log_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_Save {
            get {
                return ResourceManager.GetString("Log_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start (&amp;E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainBtn_Start {
            get {
                return ResourceManager.GetString("MainBtn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop (&amp;E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainBtn_Stop {
            get {
                return ResourceManager.GetString("MainBtn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching Interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string maxIntervalToolStripMenuItem {
            get {
                return ResourceManager.GetString("maxIntervalToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application was running in abnormal!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_abnormal_1 {
            get {
                return ResourceManager.GetString("Msg_abnormal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit to restart!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_abnormal_2 {
            get {
                return ResourceManager.GetString("Msg_abnormal_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abnormal Running Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_abnormal_Title {
            get {
                return ResourceManager.GetString("Msg_abnormal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you change the language, must be in waiting status.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Change_HaveTo_Waiting {
            get {
                return ResourceManager.GetString("Msg_Change_HaveTo_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The log will be displayed in the previous language until the application is restart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Lang_Change_Log {
            get {
                return ResourceManager.GetString("Msg_Lang_Change_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success to Stop!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Stop {
            get {
                return ResourceManager.GetString("Msg_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK (&amp;E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OKBtn {
            get {
                return ResourceManager.GetString("OKBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string radioButton0 {
            get {
                return ResourceManager.GetString("radioButton0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string radioButton1 {
            get {
                return ResourceManager.GetString("radioButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Running_Time {
            get {
                return ResourceManager.GetString("Running_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success to Save!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save_Saved {
            get {
                return ResourceManager.GetString("Save_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save. Please check log.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save_Saved_Error {
            get {
                return ResourceManager.GetString("Save_Saved_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string saveToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Search_Keyword_Label {
            get {
                return ResourceManager.GetString("Search_Keyword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can setup interval time what waiting time between search.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setInterval_label1 {
            get {
                return ResourceManager.GetString("setInterval_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed option will be waiting fixed time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setInterval_label2 {
            get {
                return ResourceManager.GetString("setInterval_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random option will be waiting random time until setup time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setInterval_label3 {
            get {
                return ResourceManager.GetString("setInterval_label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setup_ToolStripMenuItem {
            get {
                return ResourceManager.GetString("Setup_ToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Label {
            get {
                return ResourceManager.GetString("Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    - Searching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Searching {
            get {
                return ResourceManager.GetString("Status_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Error (Check log)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Searching_Error {
            get {
                return ResourceManager.GetString("Status_Searching_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... - Searching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Searching_Long {
            get {
                return ResourceManager.GetString("Status_Searching_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Searching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Start {
            get {
                return ResourceManager.GetString("Status_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Searching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Stop {
            get {
                return ResourceManager.GetString("Status_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for work...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Wait {
            get {
                return ResourceManager.GetString("Status_Wait", resourceCulture);
            }
        }
    }
}
